# Generated by Django 4.2.1 on 2023-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Disabled')], default=True),
        ),
    ]
